baseURL = 'https://boilermusicgroup.com/'
languageCode = 'en-us'
title = 'Boiler Music Group'
theme = "dream"
defaultContentLanguage = "en"

[params]
#zenMode = true
lightTheme = "emerald"
darkTheme = "forest"
avatar = "img/BoilerRecords-v2.png"
avatarDark = "img/BoilerRecords-v2-dark.png"
rss = true
email = "donald@boilermusicgroup.com"
siteStartYear = 2025
favicon = "img/favicon.png"
stickyNav = true
showTableOfContents = true
showSummaryCoverInPost = true
imageZoomableInPost = true
showPrevNextPost = true
reorderNavItems = ["about", "search", "rss", "posts", "categories", "tags"]
collapseNavItems = ["posts", "categories", "tags"]
noDefaultSummaryCover = true
# showTableOfContents = true
# showSummaryCoverInPost = true
# imageZoomableInPost = true
# showPrevNextPost = true
reorderShares = ["x", "facebook", "whatsapp"]
